name: tinysync_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+5

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.4
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  http: ^1.1.0
  url_launcher: ^6.2.1
  mask_text_input_formatter: ^2.9.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  video_player: ^2.8.10
  chewie: ^1.7.4
  web_socket_channel: ^2.4.0
  connectivity_plus: ^5.0.2
  location: ^5.0.3
  permission_handler: ^11.0.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  # ✅ Removed Firebase dependencies - no more FCM headaches!
  # firebase_core: ^2.27.0
  # firebase_messaging: ^14.9.4
  jose: ^0.3.4
  crypto: ^3.0.3
  bcrypt: ^1.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/firebase-service-account.json
